=== hollomyfoolish/lib-test/xml-xsd/src/main/resources/xsd/listbean.schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.tt.org/listbean.schema"
	xmlns:tt="http://www.tt.org/listbean.schema"
	xmlns:tns="http://www.example.org/listbean.schema"
	elementFormDefault="qualified">
	
	<element name="ListBean">
		<complexType>
			<sequence>
				<element name="Domain" type="anyType" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="person" type="tt:person"></element>
	<element name="animal" type="tt:animal"></element>
	
	<complexType name="person">
		<sequence>
			<element name="aac001" type="string"></element>
			<element name="aac002" type="string"></element>
			<element name="aac003" type="string"></element>
		</sequence>
	</complexType>
	<complexType name="animal">
		<sequence>
			<element name="name" type="string"></element>
			<element name="voice" type="string"></element>
		</sequence>
	</complexType>
</schema>

=== hollomyfoolish/lib-test/xml-xsd/src/main/resources/xsd/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tt:ListBean
	xmlns:tt="http://www.tt.org/listbean.schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tt.org/listbean.schema ./listbean.schema.xsd"
>
<tt:Domain xsi:type="tt:person">
	<tt:aac001>aac001</tt:aac001>
	<tt:aac002>aac002</tt:aac002>
	<tt:aac003>aac003</tt:aac003>
</tt:Domain>
<tt:Domain xsi:type="tt:animal">
	<tt:name>tiger</tt:name>
	<tt:voice>wo..</tt:voice>
</tt:Domain>
</tt:ListBean>
