=== hollomyfoolish/lib-test/xml-test/src/main/resources/test.schema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:allenui="http://no.such.website"
	elementFormDefault="qualified">
 
 	<xs:element name="menu" type="menu"></xs:element>
    <xs:complexType name="menu">
    	<xs:sequence>
    		<xs:element name="id" type="xs:string"></xs:element>
    		<xs:element name="text" type="xs:string"></xs:element>
    		<xs:element name="menu" type="menu" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		<xs:element name="button" type="button" minOccurs="0" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    <xs:complexType name="button">
    	<xs:sequence>
    		<xs:element name="id" type="xs:string"></xs:element>
    		<xs:element name="text" type="xs:string"></xs:element>
    		<xs:element name="action" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>
 
</xs:schema>

=== hollomyfoolish/lib-test/xml-test/src/main/resources/menu.test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://no.such.website ./test.schema2.xsd">
	<id>main menu</id>
	<text>main menu</text>
	<menu>
		<id>sub-1</id>
		<text>sub menu 1</text>
		<menu>
			<id>sub-1-1</id>
			<text>sub-1-1</text>
			<button>
				<id>btn-1-1</id>
				<text>btn 1-1</text>
				<action>action 1-1</action>
			</button>
		</menu>
	</menu>
	<menu>
		<id>sub-2</id>
		<text>sub menu 2</text>
		<menu>
			<id>sub-2-1</id>
			<text>sub-2-1</text>
			<button>
				<id>btn-2-1</id>
				<text>btn 2-1</text>
				<action>action 2-1</action>
			</button>
		</menu>
	</menu>
	<button>
		<id>main-btn</id>
		<text>main btn</text>
		<action>action main</action>
	</button>
</menu>
